### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by Redp87** [marb2000/PrintSample#1]
Getting Value does not fall within the expected range.
Under Windows 10.

**Comment by marb2000** [comment]
This interop API works on the latest Win11. Unfortunately, there is a bug in Windows10 OS that needs to be fixed. The printer team will start the OS backport to Win10. However, given the rigor of the process and the testing matrix for the OS service updates, I don't think the bug fix will be available before 3 or 4 months.

**Comment by terrycox** [comment]
We still seem to be experiencing this problem and am wondering if there is any progress on the Win10 issue.
